spring.application.name=HelloAgorApi

spring.datasource.url=jdbc:mysql://localhost:3306/hello_agorapi_0326
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# configuracion para cargar las tablas y los datos desde ficheros sql

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
